---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: sanguino
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - port: 8080
    targetPort: 8080
    name: front-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: sanguino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: front-cont
        imagePullPolicy: Always
        image: sanguino/front:1.0.0
        ports:
        - containerPort: 8080
          name: rest
        env:
        - name: API_REST_PORT
          value: "8080"
        - name: KAFKA_BROKERS
          value: kafka-svc:9092
        - name: DEBUG
          value: "service:*,server:*"
        - name: ORDER_URL
          value: http://order-svc:8080/api/order
        - name: NOTIFICATIONS_URL
          value: http://notifications-svc:8080/api/notifications
