---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv
  namespace: cadsspace
spec:
  storageClassName: kafka-cn
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/kafka_data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-pvc
  namespace: cadsspace
spec:
  storageClassName: kafka-cn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: cadsspace
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 30

      volumes:
      - name: kafka-pv-storage
        persistentVolumeClaim:
          claimName: kafka-pvc

      containers:
      - name: kafka-cont
        imagePullPolicy: Always
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
          name: server
        command:
        - sh
        - -c
        - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-${HOSTNAME##*-}.kafka-svc.cadsspace.svc.cluster.local:9092 KAFKA_BROKER_ID=${HOSTNAME##*-} /etc/confluent/docker/run"
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka-svc.cadsspace.svc.cluster.local:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zoo-0.zoo-svc.cadsspace.svc.cluster.local:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: CONFLUENT_SUPPORT_CUSTOMER_ID
          value: "anonymous"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        volumeMounts:
        - name: kafka-pv-storage
          mountPath: /var/lib/kafka

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: cadsspace
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
